services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meetsafe
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01_users.sql:/docker-entrypoint-initdb.d/01_users.sql
      - ./02_interests.sql:/docker-entrypoint-initdb.d/02_interests.sql
      - ./03_groups.sql:/docker-entrypoint-initdb.d/03_groups.sql
      - ./04_events.sql:/docker-entrypoint-initdb.d/04_events.sql
      - ./05_event_participant.sql:/docker-entrypoint-initdb.d/05_event_participant.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

volumes:
  postgres_data: